# Site settings
title: VLC-Qt
email: info@tano.si
description: >
  VLC-Qt is a free library used to connect Qt and libVLC libraries.
  It contains core classes for main media playback and also some GUI classes
  for faster media player development.
baseurl: ""
url: "http://vlc-qt.tano.si"
main_url: "http://tano.si"
projects_url: "http://projects.tano.si"
blog_url: "http://blog.tano.si"

# Build settings
markdown: kramdown
exclude: []
